name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Oh! It seems like you have an issue! Don't worry, we will respond ASAP."
        pr-message: "Trying to make your own version? Only host the game files on GitHub and the game on Pastebin."
